### PR TITLE
add funding transparency logs

### PR DESCRIPTION
**Pull request by lehnberg**
This PR implements logs that will support [funding transparency reports](https://github.com/mimblewimble/grin-pm/blob/master/notes/20190129-meeting-governance.md#decision-fund-transparency-report).

Specifically, it:
1. Gives each decision log entry a unique ID (to make it easy to reference);
2. Adds a `financials/income_log.csv`, with the first entry being today's donation from Minerbabe;
3. Adds a `financials/spending_log.csv`, with the first entry being today's 30% advance to Coinspect for the security audits;

_edit: updating based on feedback below._

### CODE REVIEW

**Comment by ignopeverell** [comment]
I wouldn't entirely discount the possibility of one activity or another, directly related to grin, that would generate revenue. Bad example but example nonetheless: auctioning the genesis block reward. So perhaps rename the donation log to revenue log and indicate in it whether it's a donation?

**Comment by lehnberg** [comment]
good point @ignopeverell, that's now been updated

**Comment by kargakis** [comment]
Should we do the same thing for spending? The security audit is not a donation to Coinspect but paying @antiochp for 3 months is a donation, right?

**Comment by lehnberg** [comment]
Hmm. Not sure. What would the purpose be? Ie why is it meaningful to distinguish between “donations” and other types of spends?

**Comment by kargakis** [comment]
> Hmm. Not sure. What would the purpose be? Ie why is it meaningful to distinguish between “donations” and other types of spends?

I don't have a legal background but based on the last gov meeting, we decided to call payments to devs such as Antioch as a donation vs a contract - see discussion starting from https://gitter.im/grin_community/Lobby?at=5c755d2147276019e981b200

**Comment by lehnberg** [comment]
Yes I’m aware. But what is the reason to distinguish the spend as such compared to other spends? The reason we would do it on the income side is because donations would affect friends of grin whilst other income would not. How is this distinction meaningful on the spend side?

**Comment by kargakis** [comment]
The sentiment in the meeting was uncertainty around legal/tax matters, that's why I think the distinction was made. It may not matter at all in the end.

**Comment by lehnberg** [comment]
@kargakis let's keep an eye on it, it's an easy add in the future. merging this for now.

**Comment by kargakis** [comment]
:+1:

**Pull request merged**
