### PR TITLE
Replace grin https donation address with slatepack address

### LINKED ISSUE #324: grin donation address failed
https://council-donations.yeastplume.org

https Security certificate expired

### PR DESCRIPTION
**Pull request by lehnberg**
Fixes #324 #325

### CODE REVIEW

**Comment by lehnberg** [comment]
@yeastplume just tried to send a test donation to the new address and it failed. Is the wallet listening?

```
$ ./grin-wallet/grin-wallet send -d grin1wm78wjsf2ws507hea4zqrcywxltjwhtgfrwzhdrr9l80l7tpz5fsj58lk0 0.1337
Password:
20200803 08:17:44.548 WARN grin_wallet_api::owner - Attempting to send transaction via TOR
20200803 08:18:11.052 WARN grin_wallet_api::owner - Unable to send transaction via TOR. Attempting alternate methods.
/home/lehnberg/.grin/main/slatepack/0da52150-52a9-4d34-a099-435df0e7e589.S1.slatepack

Slatepack data follows. Please provide this output to the other party
```

**Comment by lehnberg** [comment]
Screenshot 2021-01-11 at 16 36 44

**Comment by quentinlesceller** [comment]
Doesn't work for me 
```
20210112 09:12:01.266 DEBUG grin_wallet_impls::tor::process - Dropping TOR process
20210112 09:12:09.578 DEBUG grin_wallet_api::owner - Send (TOR): Could not send Slate via TOR: Client Callback Error: Performing version check (is recipient listening?): Request error: Cannot make request: error trying to connect: Unsuccessful reply: HostUnreachable
20210112 09:12:09.578 DEBUG grin_wallet_impls::tor::process - Dropping TOR process
20210112 09:12:09.578 DEBUG grin_wallet_api::owner - Unable to send via TOR: Client Callback Error: Performing version check (is recipient listening?): Request error: Cannot make request: error trying to connect: Unsuccessful reply: HostUnreachable
20210112 09:12:09.578 WARN grin_wallet_api::owner - Unable to send transaction via TOR
```

**Comment by yeastplume** [comment]
Sorry, accidentally killed a process.. can you try again?

**Comment by quentinlesceller** [comment]
Nope still unreachable for me.

**Comment by quentinlesceller** [comment]
Worked !

**Pull request merged**
